In [1]:
import torch
from ALBERT import ALBERT


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
input_ids = torch.randint(0,29999,(3,10)).to(device)

segment_ids = torch.IntTensor([[1]*10,[1]*5+[2]*5,[2]*10]).to(device)
input_mask = torch.BoolTensor([[0]*10,[0]*5+[1]*5,[1]*10]).to(device)

print (input_ids.shape)
print (segment_ids.shape)
print (input_mask.shape)
print (input_ids)
print (segment_ids)
print (input_mask)

torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
tensor([[27153, 11711, 13233,  6173, 20162, 15346, 14525, 28762,  6104, 27909],
        [ 9309, 24034, 15046,  6381, 21024, 17461,  2835,  4841, 13561, 28195],
        [28977,  2475, 16793,  2647,   553, 24497,  8931, 29409, 10127, 16851]],
       device='cuda:0')
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], device='cuda:0', dtype=torch.int32)
tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]],
       device='cuda:0')


In [2]:
albert_test=ALBERT(vocab_size=30000)
albert_test.to(device)
albert_test(input_ids, segment_ids, mask=input_mask)

tensor([[[-0.1460, -0.3908, -0.0000,  ...,  2.8460, -1.6517,  0.2239],
         [-0.3096, -1.0596, -1.0500,  ...,  2.7090, -1.0295,  0.3477],
         [-0.1987, -0.1221, -0.2979,  ...,  2.1282, -0.3802,  0.0000],
         ...,
         [-0.0000, -1.3833, -0.8951,  ...,  0.0000, -1.6178,  0.4568],
         [-0.0984, -0.2223, -0.0000,  ...,  1.9929, -0.6424,  0.0000],
         [-0.2785, -0.6191, -0.5724,  ...,  1.7890, -0.7874,  0.1589]],

        [[-0.7803, -0.0000,  0.3691,  ...,  1.5665,  0.0165, -0.0000],
         [-0.3866, -1.5682,  0.1901,  ...,  0.0000,  0.1333, -0.7988],
         [-0.6900, -1.4378,  0.3943,  ...,  0.5747,  0.2551, -0.2813],
         ...,
         [-0.6489, -2.1588,  0.7515,  ...,  0.0000, -0.0172, -0.0000],
         [-1.0635, -1.7951,  0.6817,  ...,  1.5353,  0.0000, -0.8055],
         [-0.8528, -2.2001,  0.0865,  ...,  1.9614,  0.3373, -1.2776]],

        [[ 0.7878, -2.4814, -0.1794,  ...,  1.5990, -0.1475, -0.3621],
         [ 0.4807, -1.6823,  0.1686,  ...,  1