In [1]:
import torch
from ALBERT import ALBERT


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
input_ids = torch.randint(0,29999,(3,10)).to(device)
segment_ids = torch.IntTensor([[1]*10,[1]*5+[2]*5,[2]*10]).to(device)
input_mask = torch.BoolTensor([[0]*10,[0]*5+[1]*5,[1]*10]).to(device)
print (input_ids.shape)
print (segment_ids.shape)
print (input_mask.shape)
print (input_ids)
print (segment_ids)
print (input_mask)

torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
tensor([[ 6761, 22228,  8767,  4286, 29848, 16322, 28359, 17100, 10682, 22755],
        [20870,  2269, 10391, 15050, 23024,  8409, 25575, 20249,  5444,  5961],
        [ 5154, 21102, 10103, 19704, 11725,  4911, 18303, 23395, 26524, 28207]],
       device='cuda:0')
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], device='cuda:0', dtype=torch.int32)
tensor([[False, False, False, False, False, False, False, False, False, False],
        [False, False, False, False, False,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]],
       device='cuda:0')


In [2]:
albert_test=ALBERT(vocab_size=30000)
albert_test.to(device)
albert_test(input_ids, segment_ids, mask=input_mask)

tensor([[[-0.6199, -2.8516,  0.3027,  ...,  0.3635, -0.9442,  0.3574],
         [-1.3641, -2.8103,  1.1503,  ...,  0.5753, -0.9070,  0.4066],
         [-1.4365, -2.8808,  1.4090,  ..., -0.1181, -0.3913,  0.3002],
         ...,
         [-0.7728, -2.2566,  1.1185,  ...,  0.1069, -0.6381,  0.0000],
         [-0.0000, -2.0809,  1.1555,  ...,  0.6799, -0.2569,  0.4244],
         [-1.0835, -3.3207,  0.6079,  ...,  0.4860, -0.5231,  0.3225]],

        [[-0.7704, -0.4743,  0.1523,  ..., -0.6005, -2.2283,  1.0936],
         [-0.8271, -0.3085,  2.5845,  ..., -0.0000, -1.4829,  0.4966],
         [-2.2542, -0.0000,  3.0311,  ..., -1.2391, -2.1443,  0.0000],
         ...,
         [-2.0692, -0.4650,  2.3428,  ..., -0.4196, -0.8654,  1.2102],
         [-1.3984, -0.0000,  0.8720,  ..., -1.2164, -2.6003,  1.0953],
         [-0.5508, -0.0000,  2.6067,  ..., -0.6327, -2.1358,  0.8840]],

        [[-0.7353, -0.1698,  0.0000,  ..., -0.8824, -1.1117,  1.4536],
         [-0.1329, -0.5374,  0.0000,  ..., -0

In [9]:
from Embeddings import ALBERTTokenEmbedding
import torch
ALBERTTokenEmbedding(vocab_size=100).token((torch.LongTensor([[1,2,3]])))

tensor([[[-1.1315e+00, -1.3824e+00, -7.4704e-02,  1.8605e+00, -2.5702e+00,
          -1.8749e+00, -1.0469e+00, -1.3554e+00,  2.8846e+00,  1.1196e+00,
           1.6326e+00, -2.3512e-01, -2.4839e-01, -8.9931e-01,  7.6161e-01,
          -3.8008e-01,  2.1435e+00, -7.3581e-01,  1.3882e+00, -1.7618e+00,
          -1.2762e+00,  8.3085e-01,  1.5421e-01, -9.8796e-01,  1.6052e+00,
           5.0553e-01, -5.7172e-01,  7.4389e-01,  2.2595e-01,  1.1976e+00,
           5.9246e-02,  7.0341e-01,  5.3462e-02, -2.3610e-02, -1.1864e+00,
           1.6253e+00,  3.3319e+00,  5.1471e-01, -1.0771e+00,  1.0891e+00,
          -9.4333e-01, -6.7561e-01, -1.7200e-01,  1.0400e+00,  6.7724e-02,
           1.1788e+00,  2.0194e+00, -5.9497e-02, -8.6833e-01,  2.2438e-01,
           2.4625e+00, -6.1385e-01, -8.2733e-03,  1.2423e+00,  4.0216e-01,
          -1.0020e-01, -4.7887e-01, -1.3091e+00,  8.1035e-01, -8.5206e-01,
           6.6679e-02,  7.6370e-01,  1.9163e-01, -6.1410e-01,  1.9863e-01,
           1.9908e+00, -1