In [1]:
import torch
from ALBERT import ALBERT

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
input_ids = torch.randint(0,29999,(3,10)).to(device)
segment_ids = torch.IntTensor([[1]*10,[1]*5+[2]*5,[2]*10]).to(device)
input_mask = torch.ByteTensor([[0]*10,[0]*5+[1]*5,[1]*10]).to(device)
print (input_ids.shape)
print (segment_ids.shape)
print (input_mask.shape)
print (input_ids)
print (segment_ids)
print (input_mask)

torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
tensor([[22603, 29094, 26425,  4740, 28638, 13064,  8845, 12303, 26787, 16634],
        [21375,  2121, 13654,  9202, 11530, 15003, 15487, 13376, 24763, 15495],
        [ 4933, 23243,  3440,  6048, 18018,  9184, 12074, 10785, 10136, 18272]],
       device='cuda:0')
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], device='cuda:0', dtype=torch.int32)
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0', dtype=torch.uint8)


In [2]:
albert_test=ALBERT(vocab_size=30000)
albert_test.to(device)
albert_test(input_ids, segment_ids, mask=input_mask)

tensor([[[-0.0254, -0.6502,  0.1421,  ...,  0.0000,  1.2010,  0.3922],
         [-0.0148, -0.2875,  0.1559,  ..., -0.6799,  0.7081,  0.0000],
         [ 0.0000, -0.6011,  0.2615,  ..., -0.0451,  0.9782,  0.4240],
         ...,
         [-0.2480,  0.0966,  0.5689,  ..., -0.2599,  0.4671,  0.2412],
         [ 0.4441, -0.3497,  0.0766,  ..., -0.7912,  0.7698,  0.2481],
         [ 0.5292, -0.9782,  0.1515,  ..., -0.6276,  1.0836,  0.6374]],

        [[ 1.7773, -1.3443, -0.3104,  ...,  1.4955, -1.4347,  0.0783],
         [ 1.8091,  0.0000, -0.1976,  ...,  2.4167, -1.2018, -0.3464],
         [ 0.2934, -2.0956, -0.5552,  ...,  0.0000, -1.5302, -1.2321],
         ...,
         [ 1.6159, -2.3950, -0.1674,  ...,  0.0000, -1.9262, -0.8608],
         [ 1.2147, -1.3560, -0.2912,  ...,  1.4389, -1.6210, -1.2904],
         [ 2.1143, -1.5429,  0.3506,  ...,  2.8200,  0.1002, -1.7218]],

        [[ 0.8098, -0.5121,  0.3600,  ...,  2.4437, -0.9954, -0.2822],
         [ 0.5011, -0.3741,  0.6016,  ...,  2