In [1]:
import torch
from ALBERT import ALBERT

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
input_idx = torch.randint(0,29999,(3,10)).to(device)
segment_idx = torch.IntTensor([[1]*10,[1]*5+[2]*5,[2]*10]).to(device)
input_mask = torch.ByteTensor([[0]*10,[0]*5+[1]*5,[1]*10]).to(device)
print (input_idx.shape)
print (segment_idx.shape)
print (input_mask.shape)
print (input_idx)
print (segment_idx)
print (input_mask)

torch.Size([3, 10])
torch.Size([3, 10])
torch.Size([3, 10])
tensor([[19482, 10940, 26702, 10668,  1679,  5078, 14102, 20786,   845, 11266],
        [ 6183, 22969, 29369,  7566,  3648, 14608,   623, 16859, 21676,  9110],
        [13552, 26528, 15214,  7877, 24214, 28178, 15943,  8540,  1133, 22627]],
       device='cuda:0')
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], device='cuda:0', dtype=torch.int32)
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], device='cuda:0', dtype=torch.uint8)


In [2]:
albert_test=ALBERT(vocab_size=30000)
albert_test.to(device)
albert_test(input_idx, segment_idx, mask=input_mask)

tensor([[[-0.0820, -0.1586, -0.1088,  ...,  1.7836,  0.3999, -0.3212],
         [-0.7560, -1.2724, -0.1078,  ...,  2.1661,  0.4731,  0.0364],
         [-0.7376,  0.0000, -0.5560,  ...,  2.0039,  0.0876, -0.1021],
         ...,
         [-0.9014, -0.1411, -0.1612,  ...,  1.3203, -0.0229, -0.4166],
         [ 0.0000, -1.7113, -0.6906,  ...,  2.1389,  0.3207,  0.0951],
         [-1.1174, -0.0623,  0.1307,  ...,  1.5086,  0.8101, -0.0490]],

        [[ 1.6444, -0.2100, -1.1235,  ...,  0.0145, -0.7074, -1.3222],
         [ 0.5272, -0.0918, -1.2473,  ...,  2.0026, -0.6385,  0.0000],
         [ 0.9157, -0.0539,  0.3174,  ...,  2.0556, -0.0969, -1.2025],
         ...,
         [ 0.1032, -0.0970,  0.0000,  ...,  3.4847, -0.1487, -1.1835],
         [ 0.4567, -0.4913,  0.2438,  ...,  2.0918, -0.5493, -1.5794],
         [ 1.5445, -0.2156, -0.8447,  ...,  0.0000, -0.3859, -0.8612]],

        [[-0.0451, -0.6930,  1.3768,  ...,  2.4732, -1.3545, -0.9469],
         [ 0.0000, -0.5478,  0.6490,  ...,  1